### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by songlinshu** [Carbonhell/FractalClockWallpaper#1]
hi,
F:\rust project\FractalClockWallpaper>wasm-opt -O3 -o fractal_wallpaper_opt.wasm pkg/fractal_wallpaper_bg.wasm
'wasm-opt' is not recognized as an internal or external command,
operable program or batch file.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

**Comment by Carbonhell** [comment]
Hi! Thanks for your interest in this project :)

wasm-opt is used to optimize the resulting .wasm binary file size. It isn't required but it helps reducing the size by about a 10%-20% margin.
wasm-opt should be automatically installed by the wasm-pack binary, did you run `cargo make build-opt` or did you manually try to run wasm-opt? If the latter, you must install wasm-pack manually first.
Otherwise, it seems like wasm-pack may have failed to find precompiled binaries of wasm-opt for your platform (you may be able to confirm this by checking if the output of the installation of wasm-pack contains something like `Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!`. By any chance, are you on an armv71 platform? In that case you may have to build wasm-opt yourself: https://github.com/rustwasm/wasm-pack/issues/913
If you don't care about optimization, you should be able to simply skip the opt step by running those two commands:
`cargo make build` to actually generate the wasm binaries, and
`cargo make python` to embed the wasm base64 in the index.html file.

Let me know if I've been of any help :)
